.\" test man page source
.\"
.\" use
.\"   groff -man -Tutf8 myautomake.1
.\" or
.\"   nroff -man hiredisccc.1
.\" to process this source
.\"
.TH HIREDIS_CCC 1 2019-03-21 XYZ "Hiredis cluster c client user manual"
.SH NAME
hiredisccc \- print information about functions
.SH SYNOPSIS
.B hiredisccc
[-v | --version] [-h | --help]
.SH DESCRIPTION
.B hiredisccc
My description 
.P
.fi
.SH OPTIONS
.IP "-v or --version"
show version and copyright
.IP "-h or --help"
display this help and exit
.SH RETURN VALUE
.IP 1
unknown or invalid argument on invocation
.IP 0
successful program execution
.SH "SEE ALSO"
.BR abc (1)
